"""empty message

Revision ID: 467889b3fcfe
Revises: 
Create Date: 2019-10-08 19:33:13.287175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '467889b3fcfe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=35), nullable=False),
    sa.Column('descricao', sa.String(length=1000), nullable=True),
    sa.Column('tipo', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('produtos')
    # ### end Alembic commands ###
