"""Adicionando sku em Produtos

Revision ID: a6e4187d6ccf
Revises: 467889b3fcfe
Create Date: 2019-10-08 19:50:50.319368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6e4187d6ccf'
down_revision = '467889b3fcfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtos', sa.Column('sku', sa.String(length=35), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produtos', 'sku')
    # ### end Alembic commands ###
